# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(725, 501)
        Dialog.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        Dialog.setStyleSheet("QWidget {\n"
"    background-image: url(\"./bg/bg.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"\n"
"")
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.push1 = QtWidgets.QPushButton(Dialog)
        self.push1.setGeometry(QtCore.QRect(10, 10, 701, 111))
        self.push1.setStyleSheet("color:#FFA500    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"")
        self.push1.setAutoDefault(True)
        self.push1.setObjectName("push1")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 150, 131, 31))
        self.pushButton.setToolTipDuration(2)
        self.pushButton.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 190, 131, 31))
        self.pushButton_2.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 230, 131, 31))
        self.pushButton_3.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 270, 131, 31))
        self.pushButton_4.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 310, 131, 31))
        self.pushButton_5.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 350, 131, 31))
        self.pushButton_6.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 390, 131, 31))
        self.pushButton_7.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(210, 150, 131, 31))
        self.pushButton_8.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(210, 190, 131, 31))
        self.pushButton_9.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(210, 230, 131, 31))
        self.pushButton_10.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(210, 270, 131, 31))
        self.pushButton_11.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 310, 131, 31))
        self.pushButton_12.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(210, 350, 131, 31))
        self.pushButton_13.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(210, 390, 131, 28))
        self.pushButton_14.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(380, 150, 141, 31))
        self.pushButton_15.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(380, 230, 141, 28))
        self.pushButton_16.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(380, 270, 141, 31))
        self.pushButton_17.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(380, 310, 141, 31))
        self.pushButton_18.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(380, 190, 138, 31))
        self.pushButton_19.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(500, 460, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("color:white    ;\n"
"font-weight:bold;\n"
"\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(380, 350, 141, 28))
        self.pushButton_21.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(380, 390, 141, 28))
        self.pushButton_22.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(570, 150, 111, 31))
        self.pushButton_23.setStyleSheet("color:#00CCFF    ;\n"
"font-weight:bold;\n"
"QPushButton {\n"
"    border: 2px solid black;   /* Viền đen */\n"
"    border-radius: 8px;       /* Bo góc (tùy chọn) */\n"
"    background-color: white;  /* Màu nền */\n"
"    color: black;             /* Màu chữ */\n"
"    padding: 5px;             /* Khoảng cách nội dung */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0; /* Màu nền khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9; /* Màu nền khi nhấn nút */\n"
"}\n"
"\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(Dialog)
        self.pushButton_24.setGeometry(QtCore.QRect(550, 190, 151, 31))
        self.pushButton_24.setStyleSheet("color:RED\n"
"    ;\n"
"font-weight:bold;\n"
"\n"
"")
        self.pushButton_24.setObjectName("pushButton_24")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(540, 230, 171, 191))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bg/Logo_PTIT_University.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.push1.setText(_translate("Dialog", "==============================================================================================================\n"
"YOUTUBE DWL OS | FACEBOOK VU KIM DONG\n"
"DEV APP BY : PHCLTRZ\n"
"==============================================================================================================\n"
"\n"
"==============================================================================================================TOOL BOX | SOFTWARE DOWNLOAD==============================================================================================================\\n\\n\n"
""))
        self.pushButton.setText(_translate("Dialog", "[1].Google Chrome"))
        self.pushButton_2.setText(_translate("Dialog", "[2].Mozilla Firefox"))
        self.pushButton_3.setText(_translate("Dialog", "[3].Brave Browser"))
        self.pushButton_4.setText(_translate("Dialog", "[4].VLC Media Player"))
        self.pushButton_5.setText(_translate("Dialog", "[5].Zoom"))
        self.pushButton_6.setText(_translate("Dialog", "[6].Microsoft Edge"))
        self.pushButton_7.setText(_translate("Dialog", "[7].Opera Browser"))
        self.pushButton_8.setText(_translate("Dialog", "[8].Winrar"))
        self.pushButton_9.setText(_translate("Dialog", "[9].Visual Studio Code"))
        self.pushButton_10.setText(_translate("Dialog", "[10].Adobe Reader"))
        self.pushButton_11.setText(_translate("Dialog", "[11].Teamviewer"))
        self.pushButton_12.setText(_translate("Dialog", "[12].OBS Studio"))
        self.pushButton_13.setText(_translate("Dialog", "[13]. Skype"))
        self.pushButton_14.setText(_translate("Dialog", "[14].Zalo"))
        self.pushButton_15.setText(_translate("Dialog", "[15].PotPlayer"))
        self.pushButton_16.setText(_translate("Dialog", "[17].Telegram Desktop"))
        self.pushButton_17.setText(_translate("Dialog", "[18].uTorrent"))
        self.pushButton_18.setText(_translate("Dialog", "[19].VMware"))
        self.pushButton_19.setText(_translate("Dialog", "[16].K-Lite Codec "))
        self.pushButton_20.setText(_translate("Dialog", "EXIT"))
        self.pushButton_21.setText(_translate("Dialog", "[20].League Of Legend"))
        self.pushButton_22.setText(_translate("Dialog", "[21].Python"))
        self.pushButton_23.setText(_translate("Dialog", "[22].Unikey"))
        self.pushButton_24.setText(_translate("Dialog", "Setup to download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
